apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-server
  template:
    metadata:
      labels:
        app: ml-server
    spec:
      containers:
      - name: ml-server
        image: roberthsheng/team6:ml-server
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ml-server
spec:
  selector:
    app: ml-server
  ports:
  - port: 5000
    targetPort: 5000
